import { test, expect } from "@playwright/test";
import { mkdir } from "node:fs/promises";
test("bridge closure, consequence, recovery, timeline and reset", async ({ page }) => {
  const errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));page.on("console",m=>{if(m.type()==="error")errors.push(m.text())});
  await page.goto("/");
  await expect(page.getByText("Local sample",{exact:true})).toBeVisible();
  await expect(page.getByRole("heading",{name:"A crossing changes an afternoon."})).toBeVisible();
  await page.getByRole("button",{name:"Close bridge at 16:15"}).click();
  await expect(page.getByText("Bridge closure locked during recovery")).toBeVisible();
  await page.getByRole("button",{name:/The photograph/}).click();
  await expect(page.getByText("This event cannot happen as planned.")).toBeVisible();
  await expect(page.getByText("16:30 → 16:55")).toBeVisible();
  await page.getByRole("button",{name:"Show original traces"}).click();
  await expect(page.getByText("Original trace",{exact:true})).toBeVisible();
  await page.getByRole("button",{name:/Harbor Gazette unsupported/}).click();
  await expect(page.getByText(/Claim unsupported by the variant/)).toBeVisible();
  await page.getByRole("button",{name:/The photograph/}).click();
  await mkdir("screenshots",{recursive:true});
  await page.screenshot({path:"screenshots/01-bridge-closed-desktop.png",fullPage:true});
  await page.getByRole("button",{name:/Keep this moment/}).click();
  await expect(page.getByText("Ways to keep the moment")).toBeVisible();
  await expect(page.getByText("Activate ferry",{exact:true})).toBeVisible();
  await expect(page.getByText(/Depart at 16:00/)).toBeVisible();
  await page.screenshot({path:"screenshots/02-recovery-preview-desktop.png",fullPage:true});
  await page.getByRole("button",{name:"Apply to my variant"}).click();
  await expect(page.getByText("The photograph can happen.")).toBeVisible();
  await expect(page.getByText("Bridge closure locked during recovery")).toBeVisible();
  await expect(page.getByText("16:30 → 16:40")).toBeVisible();
  await page.locator("#time-slider").fill("75");
  await expect(page.getByText("17:15",{exact:true}).first()).toBeVisible();
  await page.screenshot({path:"screenshots/03-recovered-desktop.png",fullPage:true});
  await page.getByRole("button",{name:"Reset variant"}).click();
  await expect(page.getByRole("button",{name:"Close bridge at 16:15"})).toBeVisible();
  await expect(page.getByText("The photograph can happen.")).toBeVisible();
  expect(errors).toEqual([]);
});
test("mobile and reduced motion keep the journey usable", async ({page})=>{await page.setViewportSize({width:390,height:844});await page.emulateMedia({reducedMotion:"reduce"});await page.goto("/");await expect(page.getByRole("button",{name:"Play"})).toBeDisabled();await page.getByRole("button",{name:"Close bridge at 16:15"}).click();await page.getByRole("button",{name:/Keep this moment/}).click();await expect(page.getByText("Ways to keep the moment")).toBeVisible();await mkdir("screenshots",{recursive:true});await page.screenshot({path:"screenshots/04-recovery-mobile.png",fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);});
test("studio explains missing Sanity configuration",async({page})=>{test.setTimeout(120000);await page.goto("/studio",{waitUntil:"domcontentloaded"});await expect(page.getByText("Configure a dedicated Sanity project to open Butterfly Studio.")).toBeVisible();});
