import { describe, expect, it } from "vitest";
import { sampleWorld } from "../fixtures/harbor";
import { applyPatch, validateWorld, type RealityPatch, type World } from "../src/world/model";
import { compare, findRoute, getEvent, simulate } from "../src/engine/simulate";
import { applyAlternative, keepThisMoment } from "../src/engine/search";
import { fromDraftDocument, toDraftDocument } from "../src/sanity/adapter";
const closure = (value=15):RealityPatch=>({worldId:sampleWorld.id,baseRevision:sampleWorld.baseRevision,operations:[{type:"setConnectionEnd",connectionId:"bridge",value}]});
const goal={eventId:"photo",time:50,placeId:"plaza",requiredTypes:["eventOccurred","entityAt","factEquals"]};
const copy=():World=>structuredClone(sampleWorld);
describe("the harbor day",()=>{
  it("calculates both days, preserves ceremony, and reevaluates the newspaper claim",()=>{const original=simulate(sampleWorld),variant=simulate(applyPatch(sampleWorld,closure()));expect(getEvent(original,"delivery").time).toBe(30);expect(getEvent(original,"setup").time).toBe(40);expect(getEvent(original,"photo").status).toBe("possible");expect(getEvent(variant,"delivery").route?.connectionIds).toEqual(["land"]);expect(getEvent(variant,"delivery").time).toBe(55);expect(getEvent(variant,"setup").time).toBe(65);expect(getEvent(variant,"photo").status).toBe("impossible");expect(getEvent(variant,"ceremony").status).toBe("possible");expect(variant.artifacts[0].compatibility).toBe("unsupported");expect(compare(original,variant).find(x=>x.id==="ceremony")?.timing).toBe("unchanged");});
  it("keeps the direct route when the crossing finishes before closure",()=>{const result=simulate(applyPatch(sampleWorld,closure(31)));expect(getEvent(result,"delivery").route?.connectionIds).toEqual(["bridge"]);expect(getEvent(result,"photo").status).toBe("possible");});
});
describe("temporal rules",()=>{
  it("checks the entire crossing and allows arrival exactly at the closing instant",()=>{const overlap=simulate(applyPatch(sampleWorld,closure(29)));expect(getEvent(overlap,"delivery").route?.connectionIds).toEqual(["land"]);const boundary=simulate(applyPatch(sampleWorld,closure(30)));expect(getEvent(boundary,"delivery").route?.connectionIds).toEqual(["bridge"]);});
  it("waits for a window and does not assume an unavailable cargo exists",()=>{const w=copy();w.connections.find(c=>c.id==="bridge")!.windows=[{start:30,end:60}];w.connections.find(c=>c.id==="land")!.enabled=false;expect(findRoute(w,"depot","plaza","van",20)?.arrive).toBe(40);w.facts.find(f=>f.id==="cargo-ready")!.interval.start=21;const result=simulate(w);expect(getEvent(result,"delivery").status).toBe("unknown");expect(result.artifacts[0].compatibility).toBe("unknown");});
  it("does not produce effects from an impossible event",()=>{const w=copy();w.facts.find(f=>f.id==="cargo-ready")!.value=false;const result=simulate(w);expect(getEvent(result,"delivery").status).toBe("impossible");expect(getEvent(result,"setup").status).toBe("impossible");expect(getEvent(result,"photo").status).toBe("impossible");});
  it("treats a prerequisite completed at the event start as satisfied",()=>{const w=copy();w.events.find(e=>e.id==="delivery")!.at=20;w.connections.find(c=>c.id==="bridge")!.enabled=false;w.connections.find(c=>c.id==="land")!.enabled=false;w.connections.find(c=>c.id==="ferry")!.enabled=true;const result=simulate(w);expect(getEvent(result,"setup").time).toBe(50);expect(getEvent(result,"photo").status).toBe("possible");});
});
describe("Keep this moment",()=>{
  it("finds both independent recoveries and rejects an ineffective departure",()=>{const search=keepThisMoment(sampleWorld,closure(),goal);expect(search.status).toBe("found");expect(search.alternatives.some(a=>a.operations.some(o=>o.type==="setEventTime"&&o.value===0))).toBe(true);expect(search.alternatives.some(a=>a.operations.some(o=>o.type==="enableConnection"))).toBe(true);expect(search.alternatives.some(a=>a.operations.some(o=>o.type==="setEventTime"&&o.value===10)&&a.operations.length===1)).toBe(false);for(const a of search.alternatives){expect(getEvent(a.result,"photo").status).toBe("possible");expect(getEvent(a.result,"photo").time).toBe(50);const patched=applyPatch(sampleWorld,{...closure(),operations:[...closure().operations,...a.operations]});expect(patched.connections.find(c=>c.id==="bridge")!.windows[0].end).toBe(15);}});
  it("distinguishes already satisfied, exhausted, interrupted and unknown",()=>{expect(keepThisMoment(sampleWorld,{...closure(),operations:[]},goal).status).toBe("already-satisfied");const w=copy();w.interventions=[];expect(keepThisMoment(w,closure(),goal).status).toBe("exhausted");expect(keepThisMoment(sampleWorld,closure(),goal,{maxCandidates:0,maxInterventions:2}).status).toBe("limit-reached");const limited=keepThisMoment(sampleWorld,closure(),goal,{maxCandidates:1,maxInterventions:2});expect(limited.status).toBe("limit-reached");expect(limited.alternatives.length).toBe(1);const partial=copy();partial.networkComplete=false;partial.connections.forEach(c=>c.enabled=false);partial.interventions=[];expect(keepThisMoment(partial,closure(),goal).status).toBe("indeterminate");});
  it("rechecks the selected alternative before applying",()=>{const found=keepThisMoment(sampleWorld,closure(),goal).alternatives[0];const next=applyAlternative(sampleWorld,closure(),goal,found);expect(getEvent(simulate(applyPatch(sampleWorld,next)),"photo").status).toBe("possible");expect(()=>applyAlternative(sampleWorld,{...closure(),baseRevision:"old"},goal,found)).toThrow();});
});
describe("data independence and integrity",()=>{
  it("uses a new data connection without engine changes",()=>{const w=copy();w.connections.push({id:"tram",worldId:w.id,from:"depot",to:"plaza",modes:["van"],duration:15,windows:[{start:0,end:120}],enabled:true,path:[[-5,-1],[4,1]]});const result=simulate(applyPatch(w,closure()));expect(getEvent(result,"delivery").route?.connectionIds).toEqual(["tram"]);expect(getEvent(result,"photo").status).toBe("possible");});
  it("ignores labels and document order, remains deterministic and immutable",()=>{const w=copy(),before=JSON.stringify(w),first=simulate(w);w.events.reverse().forEach(e=>e.name=`Changed ${e.id}`);w.connections.reverse();const second=simulate(w);expect(second.events.map(e=>[e.id,e.time,e.status,e.route?.connectionIds])).toEqual(first.events.map(e=>[e.id,e.time,e.status,e.route?.connectionIds]));expect(simulate(sampleWorld)).toEqual(simulate(sampleWorld));expect(JSON.stringify(sampleWorld)).toBe(before);});
  it("rejects broken references, mixed worlds, cycles, forbidden patches and stale revisions",()=>{const w=copy();w.events.find(e=>e.id==="photo")!.requirements.push({type:"eventOccurred",eventId:"missing"});expect(()=>validateWorld(w)).toThrow(/Missing required/);const mixed=copy();mixed.entities[0].worldId="other";expect(()=>validateWorld(mixed)).toThrow(/another world/);const cyclic=copy();cyclic.events.find(e=>e.id==="delivery")!.requirements.push({type:"eventOccurred",eventId:"photo"});expect(()=>validateWorld(cyclic)).toThrow(/Cyclic/);expect(()=>applyPatch(sampleWorld,{...closure(),operations:[{type:"enableConnection",connectionId:"bridge",value:true}]})).toThrow(/not allowed/);expect(()=>applyPatch(sampleWorld,{...closure(),baseRevision:"old"})).toThrow(/Stale/);expect(()=>applyPatch(applyPatch(sampleWorld,closure()),{...closure(),operations:[{type:"setConnectionEnd",connectionId:"bridge",value:120}]},closure().operations)).toThrow(/Locked/);});
  it("keeps visitor variants separate and round-trips structured Sanity draft content",()=>{const a=applyPatch(sampleWorld,closure());const b=simulate(sampleWorld);expect(getEvent(simulate(a),"photo").status).toBe("impossible");expect(getEvent(b,"photo").status).toBe("possible");expect(fromDraftDocument(toDraftDocument(sampleWorld))).toEqual(sampleWorld);});
});
