"use client";
import dynamic from "next/dynamic";
import { useEffect, useMemo, useState } from "react";
import { applyPatch, type Operation, type RealityPatch, type World } from "../world/model";
import { compare, formatTime, getEvent, simulate } from "../engine/simulate";
import { applyAlternative, keepThisMoment, type Goal, type SearchResult } from "../engine/search";
const Diorama = dynamic(() => import("../scene/Diorama"), { ssr: false, loading: () => <div className="scene-loading">Building the neighborhood…</div> });
function webglAvailable() { try { const canvas = document.createElement("canvas"); return Boolean(canvas.getContext("webgl2") || canvas.getContext("webgl")); } catch { return false; } }
export default function Experience({initialWorld,source,error}:{initialWorld:World;source:string;error?:string}) {
  const displayTime=(minute:number|null)=>formatTime(minute,initialWorld.originMinute);
  const featured=initialWorld.events.find(e=>e.id===initialWorld.featuredMoment.eventId)!;
  const goal:Goal={eventId:featured.id,time:featured.at!,placeId:initialWorld.featuredMoment.placeId,requiredTypes:[...new Set(featured.requirements.map(r=>r.type))]};
  const [patch,setPatch] = useState<RealityPatch>({worldId:initialWorld.id,baseRevision:initialWorld.baseRevision,operations:[]});
  const [time,setTime] = useState(20), [playing,setPlaying] = useState(false), [compareOn,setCompareOn] = useState(false), [selected,setSelected] = useState<string|null>("bridge"), [search,setSearch] = useState<SearchResult|null>(null), [preview,setPreview] = useState<string|null>(null), [webgl,setWebgl] = useState<boolean|null>(null), [reduced,setReduced] = useState(false), [newVersion,setNewVersion] = useState(false);
  useEffect(() => { const media=window.matchMedia("(prefers-reduced-motion: reduce)"); const frame=window.requestAnimationFrame(()=>{setWebgl(webglAvailable());setReduced(media.matches)}); const listener=()=>setReduced(media.matches); media.addEventListener("change",listener); return ()=>{window.cancelAnimationFrame(frame);media.removeEventListener("change",listener)}; },[]);
  useEffect(()=>{ if(!playing || reduced) return; const id=window.setInterval(()=>setTime(t=>t>=initialWorld.horizon?(setPlaying(false),initialWorld.horizon):t+1),500); return ()=>clearInterval(id); },[playing,reduced,initialWorld.horizon]);
  useEffect(()=>{ const handler=(e:KeyboardEvent)=>{ if(e.target instanceof HTMLInputElement) return; if(e.code==="Space"){e.preventDefault();setPlaying(x=>!x);} if(e.code==="ArrowRight")setTime(t=>Math.min(initialWorld.horizon,t+1)); if(e.code==="ArrowLeft")setTime(t=>Math.max(0,t-1)); };window.addEventListener("keydown",handler);return()=>window.removeEventListener("keydown",handler);},[initialWorld.horizon]);
  useEffect(()=>{if(source!=="Live Sanity")return;const check=async()=>{try{const response=await fetch("/api/version");if(!response.ok)return;const data=await response.json() as {revisionId:string|null};if(data.revisionId&&data.revisionId!==initialWorld.baseRevision)setNewVersion(true)}catch{}};const timer=window.setInterval(check,60000);return()=>window.clearInterval(timer)},[source,initialWorld.baseRevision]);
  const original=useMemo(()=>simulate(initialWorld),[initialWorld]);
  const world=useMemo(()=>applyPatch(initialWorld,patch),[initialWorld,patch]);
  const variant=useMemo(()=>simulate(world),[world]);
  const differences=useMemo(()=>compare(original,variant),[original,variant]);
  const closed=patch.operations.some(o=>o.type==="setConnectionEnd");
  const target=getEvent(variant,goal.eventId), delivery=getEvent(variant,"delivery"), setup=getEvent(variant,"setup"), ceremony=getEvent(variant,"ceremony");
  const artifact=variant.artifacts[0];
  const selectedEvent=variant.events.find(e=>e.id===selected);
  const selectedConnection=world.connections.find(c=>c.id===selected);
  const selectedEntity=world.entities.find(e=>e.id===selected);
  const chosen=search?.alternatives.find(a=>a.id===preview);
  const shown=chosen?.result ?? variant;
  const changeClosure=()=>{ const operations:Operation[]=closed?[]:[{type:"setConnectionEnd",connectionId:initialWorld.visitorClosure.connectionId,value:initialWorld.visitorClosure.end}]; setPatch({worldId:initialWorld.id,baseRevision:initialWorld.baseRevision,operations});setSearch(null);setPreview(null);setSelected(initialWorld.visitorClosure.connectionId);setTime(20); };
  const find=()=>{const result=keepThisMoment(initialWorld,patch,goal);setSearch(result);setPreview(result.alternatives[0]?.id??null);setSelected(goal.eventId);setTime(goal.time);};
  const apply=()=>{if(!chosen)return;const next=applyAlternative(initialWorld,patch,goal,chosen);setPatch(next);setSearch(null);setPreview(null);setTime(goal.time);};
  const reset=()=>{setPatch({worldId:initialWorld.id,baseRevision:initialWorld.baseRevision,operations:[]});setSearch(null);setPreview(null);setTime(20);setSelected("bridge");setPlaying(false);};
  return <main className="experience">
    <header className="topbar"><div className="brand"><span className="brand-icon">✳</span><div><strong>BUTTERFLY</strong><small>Change the world. Keep the moment.</small></div></div><div className="top-actions"><span className="source">{source}</span><button className="quiet" onClick={()=>setCompareOn(x=>!x)} aria-pressed={compareOn}>{compareOn?"Hide original traces":"Show original traces"}</button></div></header>
    {error&&<div className="error" role="alert">Live Sanity connection error: {error}</div>}{newVersion&&<div className="error" role="status">A new world revision is available. Your variant remains on this snapshot; reload to begin again.</div>}
    <section className="workspace"><div className="scene-shell"><div className="scene-meta"><span>{initialWorld.title.toUpperCase()}</span><strong>{displayTime(time)}</strong></div>{webgl===false?<div className="fallback"><h2>3D view unavailable</h2><p>WebGL could not start. The timeline and all story controls remain available below.</p><p>At {displayTime(time)}, the delivery is {delivery.status} and the photograph is {target.status}.</p></div>:<Diorama world={world} variant={shown} original={original} time={time} compare={compareOn} preview={Boolean(chosen)} selected={selected} onSelect={setSelected}/>}<div className="scene-legend">{!chosen&&<span><i className="swatch variant"/>Variant route</span>}{compareOn&&<span><i className="swatch original"/>Original trace</span>}{chosen&&<span><i className="swatch alternative"/>Alternative preview</span>}{compareOn&&target.status==="impossible"&&<span>○ Missed photo composition</span>}</div></div>
    <aside className="side"><div className="eyebrow">ONE CHANGE, MANY CONSEQUENCES</div><h1>A crossing changes an afternoon.</h1><p className="intro">Move the bridge closure earlier. Follow the delivery, then preserve the photograph without reopening the bridge.</p><button className={closed?"action secondary":"action"} onClick={changeClosure}>{closed?"Restore bridge schedule":`Close bridge at ${displayTime(initialWorld.visitorClosure.end)}`}</button>{closed&&<span className="lock">✳ Bridge closure locked during recovery</span>}
      <div className="event-list"><div className="section-label">THE DAY <span>ORIGINAL → VARIANT</span></div>{["delivery","setup","photo","ceremony"].map(id=>{const row=differences.find(x=>x.id===id)!;return <button key={id} className={`event-row ${selected===id?"active":""}`} onClick={()=>{setSelected(id);setTime(id===goal.eventId?goal.time:row.variant.time??20)}}><span className="event-status" data-state={row.variant.status}>{row.variant.status==="possible"?"●":row.variant.status==="unknown"?"?":"×"}</span><span><strong>{row.variant.name}</strong><small>{row.variant.status==="impossible"?"Moment missed":row.timing==="unchanged"?"On schedule":row.timing}</small></span><b>{displayTime(row.original.time)} <em>→</em> {displayTime(row.variant.time)}</b></button>})}<button className="gazette-row" onClick={()=>setSelected("gazette")}>Harbor Gazette <strong>{artifact.compatibility}</strong></button></div>
      <div className="inspector"><div className="section-label">INSPECTOR</div><h2>{selectedEvent?.name??selectedConnection?.id??selectedEntity?.name??(selected==="gazette"?"Harbor Gazette":"Select a place or moment")}</h2>{selectedEvent?<><p>{selectedEvent.status==="possible"?"This event can happen.":selectedEvent.status==="unknown"?"Available data cannot settle this event.":"This event cannot happen as planned."}</p>{selectedEvent.reasons.filter(r=>r.status!=="possible").map((r,i)=><div className="reason" key={i}><strong>{r.requirement.type}</strong><span>Observed: {r.observed}</span><small>Caused by: {r.causes.join(", ")||"missing input"}</small></div>)}</>:selectedConnection?<p>{selectedConnection.enabled?"Available":"Inactive"} · {selectedConnection.duration} minute crossing · closes {displayTime(selectedConnection.windows[0].end)}</p>:selected==="gazette"?<p>{artifact.compatibility==="unsupported"?"Claim unsupported by the variant.":"Claim supported."} “{initialWorld.artifacts[0].body}”</p>:<p>Click an event or an element in the town to inspect it.</p>}</div>
    </aside></section>
    <section className="bottom"><div className="timeline"><button className="play" onClick={()=>setPlaying(x=>!x)} disabled={reduced} aria-label={playing?"Pause":"Play"}>{playing?"Ⅱ":"▶"}</button><label htmlFor="time-slider">TIME <strong>{displayTime(time)}</strong></label><input id="time-slider" type="range" min="0" max={initialWorld.horizon} value={time} onChange={e=>setTime(Number(e.target.value))}/><span>{displayTime(initialWorld.horizon)}</span><button className="quiet" onClick={reset}>Reset variant</button></div><div className="moment"><div><span className="eyebrow">THE MOMENT TO KEEP</span><h2>{target.status==="possible"?"The photograph can happen.":"The photograph is now a missed moment."}</h2><p>{displayTime(goal.time)} · {initialWorld.entities.find(e=>e.id===goal.placeId)?.name} · Photographer, couple and floral setup</p>{target.status==="impossible"&&<small>Original composition remains here as a reference. The missing flowers are not present in the variant.</small>}</div><button className="keep" onClick={find}>Keep this moment <span>↗</span></button></div>
    {search&&<div className="alternatives"><div className="alternative-heading"><div><span className="eyebrow">VERIFIED IN THE ENGINE</span><h2>{search.status==="found"?"Ways to keep the moment":search.status==="limit-reached"&&search.alternatives.length?"Verified options from a partial search":search.status==="already-satisfied"?"Already possible":"No verified alternative"}</h2></div><button className="quiet" onClick={()=>{setSearch(null);setPreview(null)}}>Close</button></div><p className="method">Search checked {search.examined} of {search.domainSize} candidates, at most {search.maxInterventions} interventions and {search.maxCandidates} candidates. Ranked by fewer changes, then smaller time shifts. {search.status==="limit-reached"&&"The limit was reached; this does not prove impossibility."}</p><div className="cards">{search.alternatives.map((a,i)=><button key={a.id} className={`alternative ${preview===a.id?"chosen":""}`} onClick={()=>setPreview(a.id)}><span>OPTION 0{i+1}</span><strong>{a.operations.map(o=>o.type==="setEventTime"?`Depart at ${displayTime(o.value)}`:`Activate ${o.connectionId}`).join(" + ")}</strong><small>Delivery {displayTime(getEvent(a.result,"delivery").time)} · Setup {displayTime(getEvent(a.result,"setup").time)} · Photo {getEvent(a.result,goal.eventId).status}</small></button>)}</div>{chosen&&<div className="apply-row"><p>Preview only. The bridge stays closed; other effects remain visible in the timeline.</p><button className="action" onClick={apply}>Apply to my variant</button></div>}</div>}
    <div className="sr-summary" aria-live="polite">Variant: delivery {displayTime(delivery.time)}, setup {displayTime(setup.time)}, photograph {target.status}, ceremony {ceremony.status}. Newspaper claim {artifact.compatibility}.</div></section>
  </main>;
}
