import { validateWorld, type World } from "../world/model";

const keyed = <T extends object>(items:T[]) => items.map((item,i)=>({_key:String(i),...item}));
const json=(value:string|number|boolean)=>JSON.stringify(value);
const parsed=(value:string)=>JSON.parse(value) as string|number|boolean;
type RecordValue=Record<string,unknown>;
const rec=(value:unknown)=>value as RecordValue;
const list=(value:unknown)=>value as RecordValue[];
const primitive=(value:unknown)=>value as string;
const clean=(value:unknown):unknown=>{if(Array.isArray(value))return value.map(clean);if(value&&typeof value==="object")return Object.fromEntries(Object.entries(value).filter(([k])=>k!=="_key"&&k!=="_type").map(([k,v])=>[k,clean(v)]));return value;};
export function toDraftDocument(world:World){return {_id:`butterfly.world.${world.id}`,_type:"butterflyWorldDraft",worldId:world.id,baseRevision:world.baseRevision,title:world.title,origin:world.origin,originMinute:world.originMinute,horizon:world.horizon,networkComplete:world.networkComplete,closureEditableConnectionIds:world.closureEditableConnectionIds,visitorClosure:{...world.visitorClosure,_type:"butterflyVisitorClosure"},featuredMoment:{...world.featuredMoment,_type:"butterflyFeaturedMoment"},entities:keyed(world.entities.map(e=>({...e,_type:"butterflyEntity",visual:{...e.visual,_type:"butterflyVisual",position:e.visual.position?{_type:"butterflyPoint",x:e.visual.position[0],z:e.visual.position[1]}:undefined}}))),connections:keyed(world.connections.map(c=>({...c,_type:"butterflyConnection",windows:keyed(c.windows.map(w=>({...w,_type:"butterflyInterval"}))),path:keyed(c.path.map(([x,z])=>({_type:"butterflyPoint",x,z})))}))),facts:keyed(world.facts.map(f=>({id:f.id,worldId:f.worldId,key:f.key,valueJson:json(f.value),interval:{...f.interval,_type:"butterflyInterval"},_type:"butterflyFact"}))),events:keyed(world.events.map(e=>({id:e.id,worldId:e.worldId,kind:e.kind,name:e.name,at:e.at,afterEventId:e.afterEventId,delay:e.delay,actorIds:e.actorIds,from:e.from,to:e.to,mode:e.mode,_type:"butterflyEvent",requirements:keyed(e.requirements.map(r=>({...r,operator:r.type,type:undefined,valueJson:r.type==="factEquals"?json(r.value):undefined,_type:"butterflyRequirement"}))),effects:keyed(e.effects.map(effect=>({key:effect.key,valueJson:json(effect.value),_type:"butterflyEffect"})))}))),artifacts:keyed(world.artifacts.map(a=>({...a,_type:"butterflyArtifact",claims:keyed(a.claims.map(c=>({...c,_type:"butterflyClaim"})))}))),interventions:keyed(world.interventions.map(i=>i.type==="setEventTime"?{_type:"butterflyIntervention",kind:i.type,eventId:i.eventId,timeValues:i.values,minAvailableAt:i.precondition.minAvailableAt}:{_type:"butterflyIntervention",kind:i.type,connectionId:i.connectionId,booleanValues:i.values,requiredMode:i.precondition.requiredMode}))};}
export function fromDraftDocument(raw:unknown):World{
  const d=rec(clean(raw));
  return validateWorld({id:d.worldId,baseRevision:d.baseRevision,title:d.title,origin:d.origin,originMinute:d.originMinute,horizon:d.horizon,networkComplete:d.networkComplete,closureEditableConnectionIds:d.closureEditableConnectionIds,visitorClosure:d.visitorClosure,featuredMoment:d.featuredMoment,entities:list(d.entities).map(e=>({...e,visual:{...rec(e.visual),position:e.visual&&rec(e.visual).position?[rec(rec(e.visual).position).x,rec(rec(e.visual).position).z]:undefined}})),connections:list(d.connections).map(c=>({...c,path:list(c.path).map(p=>[p.x,p.z])})),facts:list(d.facts).map(f=>({id:f.id,worldId:f.worldId,key:f.key,value:parsed(primitive(f.valueJson)),interval:f.interval,source:"input"})),events:list(d.events).map(e=>({...e,requirements:list(e.requirements).map(r=>r.operator==="factEquals"?{type:r.operator,key:r.key,value:parsed(primitive(r.valueJson))}:r.operator==="entityAt"?{type:r.operator,entityId:r.entityId,placeId:r.placeId}:{type:r.operator,eventId:r.eventId}),effects:list(e.effects).map(effect=>({key:effect.key,value:parsed(primitive(effect.valueJson))}))})),artifacts:d.artifacts,interventions:list(d.interventions).map(i=>i.kind==="setEventTime"?{type:i.kind,eventId:i.eventId,values:i.timeValues,precondition:{minAvailableAt:i.minAvailableAt}}:{type:i.kind,connectionId:i.connectionId,values:i.booleanValues,precondition:{requiredMode:i.requiredMode}})});
}
