import { defineField, defineType } from "sanity";
const str=(name:string,title=name)=>defineField({name,title,type:"string"});
const num=(name:string,title=name)=>defineField({name,title,type:"number"});
const bool=(name:string,title=name)=>defineField({name,title,type:"boolean"});
const arr=(name:string,of:string,title=name)=>defineField({name,title,type:"array",of:[{type:of}]});
const interval=defineType({name:"butterflyInterval",title:"Availability interval",type:"object",fields:[num("start"),num("end")]});
const point=defineType({name:"butterflyPoint",title:"Map point",type:"object",fields:[num("x"),num("z")]});
const visual=defineType({name:"butterflyVisual",title:"Visual",type:"object",fields:[str("kind"),str("color"),{name:"position",type:"butterflyPoint"}]});
const entity=defineType({name:"butterflyEntity",title:"Entity",type:"object",fields:[str("id"),str("worldId"),str("kind"),str("name"),str("initialPlaceId"),{name:"visual",type:"butterflyVisual"}]});
const connection=defineType({name:"butterflyConnection",title:"Connection",type:"object",fields:[str("id"),str("worldId"),str("from"),str("to"),arr("modes","string"),num("duration"),arr("windows","butterflyInterval"),bool("enabled"),arr("path","butterflyPoint")]});
const fact=defineType({name:"butterflyFact",title:"Input fact",type:"object",fields:[str("id"),str("worldId"),str("key"),str("valueJson","JSON primitive value"),{name:"interval",type:"butterflyInterval"}]});
const requirement=defineType({name:"butterflyRequirement",title:"Typed requirement",type:"object",fields:[str("operator","Operator: eventOccurred, entityAt, factEquals"),str("eventId"),str("entityId"),str("placeId"),str("key"),str("valueJson","JSON primitive value")]});
const effect=defineType({name:"butterflyEffect",title:"Effect",type:"object",fields:[str("key"),str("valueJson","JSON primitive value")]});
const event=defineType({name:"butterflyEvent",title:"Event",type:"object",fields:[str("id"),str("worldId"),str("kind"),str("name"),num("at"),str("afterEventId"),num("delay"),arr("requirements","butterflyRequirement"),arr("actorIds","string"),str("from"),str("to"),str("mode"),arr("effects","butterflyEffect")]});
const claim=defineType({name:"butterflyClaim",title:"Claim",type:"object",fields:[str("eventId"),bool("occurred")]});
const artifact=defineType({name:"butterflyArtifact",title:"Story artifact",type:"object",fields:[str("id"),str("worldId"),str("title"),{name:"body",type:"text"},arr("claims","butterflyClaim")]});
const intervention=defineType({name:"butterflyIntervention",title:"Allowed intervention",type:"object",fields:[str("kind","Kind: setEventTime or enableConnection"),str("eventId"),str("connectionId"),arr("timeValues","number"),arr("booleanValues","boolean"),num("minAvailableAt"),str("requiredMode")]});
const closure=defineType({name:"butterflyVisitorClosure",title:"Visitor closure",type:"object",fields:[str("connectionId"),num("end")]});
const moment=defineType({name:"butterflyFeaturedMoment",title:"Featured moment",type:"object",fields:[str("eventId"),str("placeId")]});
const draft=defineType({name:"butterflyWorldDraft",title:"Butterfly world authoring",type:"document",fields:[str("worldId"),str("baseRevision"),str("title"),str("origin"),num("originMinute"),num("horizon"),bool("networkComplete"),arr("closureEditableConnectionIds","string"),{name:"visitorClosure",type:"butterflyVisitorClosure"},{name:"featuredMoment",type:"butterflyFeaturedMoment"},arr("entities","butterflyEntity"),arr("connections","butterflyConnection"),arr("facts","butterflyFact"),arr("events","butterflyEvent"),arr("artifacts","butterflyArtifact"),arr("interventions","butterflyIntervention")]});
const revision=defineType({name:"butterflyWorldRevision",title:"Frozen Butterfly revision",type:"document",fields:[str("worldId"),str("revisionId"),{name:"snapshotJson",type:"text",readOnly:true},{name:"createdAt",type:"datetime",readOnly:true}]});
const pointer=defineType({name:"butterflyWorldPointer",title:"Active Butterfly world",type:"document",fields:[str("worldId"),str("activeRevisionId")]});
export const schemaTypes=[interval,point,visual,entity,connection,fact,requirement,effect,event,claim,artifact,intervention,closure,moment,draft,revision,pointer];
