import { defineField, defineType } from "sanity";

const stringField = (name: string, title = name) => defineField({ name, title, type: "string" });
const numberField = (name: string, title = name) => defineField({ name, title, type: "number" });
const booleanField = (name: string, title = name) => defineField({ name, title, type: "boolean" });
const arrayField = (name: string, of: string, title = name) => defineField({ name, title, type: "array", of: [{ type: of }] });

const interval = defineType({ name: "butterflyInterval", title: "Availability interval", type: "object", fields: [numberField("start"), numberField("end")] });
const point = defineType({ name: "butterflyPoint", title: "Map point", type: "object", fields: [numberField("x"), numberField("z")] });
const visual = defineType({ name: "butterflyVisual", title: "Visual", type: "object", fields: [stringField("kind"), stringField("color"), { name: "position", type: "butterflyPoint" }] });
const entity = defineType({ name: "butterflyEntity", title: "Entity", type: "object", fields: [stringField("id"), stringField("worldId"), stringField("kind"), stringField("name"), stringField("initialPlaceId"), { name: "visual", type: "butterflyVisual" }] });
const segment = defineType({ name: "butterflyRouteSegment", title: "Timed visual route segment", type: "object", fields: [stringField("role"), numberField("duration"), arrayField("path", "butterflyPoint")] });
const connection = defineType({ name: "butterflyConnection", title: "Connection", type: "object", fields: [stringField("id"), stringField("worldId"), stringField("label", "Display label"), stringField("from"), stringField("to"), arrayField("modes", "string"), numberField("duration"), arrayField("windows", "butterflyInterval"), booleanField("enabled"), arrayField("path", "butterflyPoint"), arrayField("segments", "butterflyRouteSegment", "Timed visual segments")] });
const fact = defineType({ name: "butterflyFact", title: "Input fact", type: "object", fields: [stringField("id"), stringField("worldId"), stringField("key"), stringField("valueJson", "JSON primitive value"), { name: "interval", type: "butterflyInterval" }] });
const requirement = defineType({ name: "butterflyRequirement", title: "Typed requirement", type: "object", fields: [stringField("operator", "Operator: eventOccurred, entityAt, factEquals"), stringField("eventId"), stringField("entityId"), stringField("placeId"), stringField("key"), stringField("valueJson", "JSON primitive value")] });
const effect = defineType({ name: "butterflyEffect", title: "Effect", type: "object", fields: [stringField("key"), stringField("valueJson", "JSON primitive value")] });
const event = defineType({ name: "butterflyEvent", title: "Event", type: "object", fields: [stringField("id"), stringField("worldId"), stringField("kind"), stringField("name"), numberField("at"), stringField("afterEventId"), numberField("delay"), arrayField("requirements", "butterflyRequirement"), arrayField("actorIds", "string"), stringField("from"), stringField("to"), stringField("mode"), arrayField("effects", "butterflyEffect")] });
const claim = defineType({ name: "butterflyClaim", title: "Story claim", type: "object", fields: [stringField("eventId"), booleanField("occurred")] });
const artifact = defineType({ name: "butterflyArtifact", title: "Story artifact", type: "object", fields: [stringField("id"), stringField("worldId"), stringField("title"), { name: "body", type: "text" }, arrayField("claims", "butterflyClaim")] });
const intervention = defineType({ name: "butterflyIntervention", title: "Allowed intervention", type: "object", fields: [stringField("kind", "Kind: setEventTime or enableConnection"), stringField("eventId"), stringField("connectionId"), arrayField("timeValues", "number"), arrayField("booleanValues", "boolean"), numberField("minAvailableAt"), stringField("requiredMode")] });
const closure = defineType({ name: "butterflyVisitorClosure", title: "Visitor closure", type: "object", fields: [stringField("connectionId"), numberField("end")] });
const compositionEntity = defineType({ name: "butterflyCompositionEntity", title: "Framed actor or prop", type: "object", fields: [stringField("entityId"), { name: "position", type: "butterflyPoint" }] });
const composition = defineType({ name: "butterflyMomentComposition", title: "Moment frame composition", type: "object", fields: [{ name: "photographerPosition", type: "butterflyPoint" }, arrayField("subjectPositions", "butterflyCompositionEntity"), arrayField("propPositions", "butterflyCompositionEntity")] });
const moment = defineType({ name: "butterflyFeaturedMoment", title: "Featured moment and composition", type: "object", fields: [stringField("eventId"), stringField("placeId"), stringField("arrangementEventId"), stringField("photographerEntityId"), arrayField("subjectEntityIds", "string"), arrayField("propEntityIds", "string"), { name: "composition", type: "butterflyMomentComposition" }] });
const roles = defineType({ name: "butterflyPresentationRoles", title: "Scene and story bindings", type: "object", fields: [stringField("deliveryEventId"), stringField("setupEventId"), stringField("ceremonyEventId"), stringField("courierEntityId"), stringField("vehicleEntityId"), stringField("floralEntityId"), stringField("depotPlaceId"), stringField("plazaPlaceId"), stringField("pierPlaceId"), stringField("landingPlaceId"), stringField("storyArtifactId")] });
const presentation = defineType({ name: "butterflyPresentation", title: "Presentation order and roles", type: "object", fields: [arrayField("eventOrder", "string"), { name: "roles", type: "butterflyPresentationRoles" }] });
const draft = defineType({ name: "butterflyWorldDraft", title: "Butterfly world authoring", type: "document", fields: [stringField("worldId"), stringField("baseRevision"), stringField("title"), stringField("origin"), numberField("originMinute"), numberField("horizon"), booleanField("networkComplete"), arrayField("closureEditableConnectionIds", "string"), { name: "visitorClosure", type: "butterflyVisitorClosure" }, { name: "featuredMoment", type: "butterflyFeaturedMoment" }, { name: "presentation", type: "butterflyPresentation" }, arrayField("entities", "butterflyEntity"), arrayField("connections", "butterflyConnection"), arrayField("facts", "butterflyFact"), arrayField("events", "butterflyEvent"), arrayField("artifacts", "butterflyArtifact"), arrayField("interventions", "butterflyIntervention")] });
const revision = defineType({ name: "butterflyWorldRevision", title: "Frozen Butterfly revision", type: "document", fields: [stringField("worldId"), stringField("revisionId"), { name: "snapshotJson", type: "text", readOnly: true }, { name: "createdAt", type: "datetime", readOnly: true }] });
const pointer = defineType({ name: "butterflyWorldPointer", title: "Active Butterfly world", type: "document", fields: [stringField("worldId"), stringField("activeRevisionId")] });

export const schemaTypes = [interval, point, visual, entity, segment, connection, fact, requirement, effect, event, claim, artifact, intervention, closure, compositionEntity, composition, moment, roles, presentation, draft, revision, pointer];
