"use client";

import { Canvas, useFrame } from "@react-three/fiber";
import { useEffect, useMemo, useRef } from "react";
import * as THREE from "three";
import type { Simulation } from "../engine/simulate";
import type { World } from "../world/model";

const water = "#9eb9b7", ground = "#e5d7bb", terracotta = "#b96954", cream = "#f0e3ca";
function Box({ position, args, color, onClick, transparent, opacity }: { position: [number,number,number]; args: [number,number,number]; color: string; onClick?: () => void; transparent?: boolean; opacity?: number }) { return <mesh position={position} onClick={onClick} castShadow receiveShadow><boxGeometry args={args}/><meshStandardMaterial color={color} transparent={transparent} opacity={opacity}/></mesh>; }
function Building({ x, z, color, roof, label, onClick }: { x:number; z:number; color:string; roof:string; label:string; onClick?: () => void }) { return <group onClick={onClick} name={label}><Box position={[x,0.72,z]} args={[1.5,1.45,1.3]} color={color}/><mesh position={[x,1.65,z]} rotation={[0,Math.PI/4,0]} castShadow><coneGeometry args={[1.18,0.72,4]}/><meshStandardMaterial color={roof}/></mesh>{[-0.38,0.38].map(a => <Box key={a} position={[x+a,0.85,z+0.66]} args={[0.25,0.32,0.035]} color="#5c8286"/>)}<Box position={[x,0.23,z+0.68]} args={[0.36,0.46,0.04]} color="#8c6b55"/></group>; }
function Tree({ x,z,s=1 }: {x:number;z:number;s?:number}) { return <group position={[x,0,z]}><mesh position={[0,0.45*s,0]} castShadow><cylinderGeometry args={[0.08*s,0.12*s,0.9*s,6]}/><meshStandardMaterial color="#85664c"/></mesh><mesh position={[0,1.1*s,0]} castShadow><icosahedronGeometry args={[0.52*s,0]}/><meshStandardMaterial color="#6f9381" flatShading/></mesh></group>; }
function Person({ x,z,color,selected,onClick }: {x:number;z:number;color:string;selected?:boolean;onClick?:()=>void}) { return <group position={[x,0,z]} onClick={onClick}><mesh position={[0,0.43,0]} castShadow><cylinderGeometry args={[0.13,0.18,0.68,8]}/><meshStandardMaterial color={color}/></mesh><mesh position={[0,0.86,0]} castShadow><sphereGeometry args={[0.16,12,8]}/><meshStandardMaterial color="#d7aa86"/></mesh>{selected && <mesh rotation={[-Math.PI/2,0,0]} position={[0,0.025,0]}><ringGeometry args={[0.28,0.35,32]}/><meshBasicMaterial color="#f6d583" side={THREE.DoubleSide}/></mesh>}</group>; }
function Line({ points,color,opacity=1,dashed=false }: {points:[number,number][];color:string;opacity?:number;dashed?:boolean}) { const line=useMemo(()=>{const curve=points.map(([x,z])=>new THREE.Vector3(x,0.09,z));const geometry=new THREE.BufferGeometry().setFromPoints(curve);const material=dashed?new THREE.LineDashedMaterial({color,transparent:true,opacity,dashSize:0.25,gapSize:0.16}):new THREE.LineBasicMaterial({color,transparent:true,opacity});const result=new THREE.Line(geometry,material);result.computeLineDistances();return result},[points,color,opacity,dashed]);useEffect(()=>()=>{line.geometry.dispose();(line.material as THREE.Material).dispose()},[line]);return <primitive object={line}/>; }
function CameraRig(){const lastWidth=useRef(0);useFrame(({camera,size})=>{if(lastWidth.current===size.width)return;const orthographic=camera as THREE.OrthographicCamera;orthographic.zoom=size.width<600?23:size.width<950?40:65;orthographic.updateProjectionMatrix();lastWidth.current=size.width});return null;}
function Van({ route,time,ghost,boat,onClick }: {route?: {depart:number;arrive:number;path:[number,number][]};time:number;ghost?:boolean;boat?:boolean;onClick?:()=>void}) { const ref = useRef<THREE.Group>(null); useFrame(() => { if (!ref.current) return; const path = route?.path ?? [[-5,-1],[4,1]]; const progress = route ? Math.max(0,Math.min(1,(time-route.depart)/(route.arrive-route.depart))) : 0; const position = progress*(path.length-1), index = Math.min(path.length-2,Math.floor(position)), fraction=position-index; ref.current.position.set(path[index][0]+(path[index+1][0]-path[index][0])*fraction,0.15,path[index][1]+(path[index+1][1]-path[index][1])*fraction); }); return <group ref={ref} onClick={onClick}>{boat&&route&&time>=route.depart&&time<route.arrive&&<Box position={[0,0.05,0]} args={[0.95,0.12,0.54]} color="#776c5a"/>}<Box position={[0,0.22,0]} args={[0.62,0.32,0.34]} color={ghost?"#f6e3bc":"#c97656"} transparent={ghost} opacity={ghost?0.42:1}/><Box position={[-0.1,0.43,0]} args={[0.3,0.21,0.32]} color={ghost?"#f6e3bc":"#f5e6c9"} transparent={ghost} opacity={ghost?0.42:1}/>{[-0.21,0.21].map(x=><mesh key={x} position={[x,0.07,0.2]} rotation={[Math.PI/2,0,0]}><cylinderGeometry args={[0.09,0.09,0.05,12]}/><meshStandardMaterial color="#444d4e" transparent={ghost} opacity={ghost?0.4:1}/></mesh>)}</group>; }
function WorldScene({ world, variant, original, time, compare, preview, selected, onSelect }: { world:World; variant:Simulation; original:Simulation; time:number; compare:boolean; preview:boolean; selected:string|null; onSelect:(id:string)=>void }) {
  const delivery = variant.events.find(e=>e.id==="delivery")?.route, originalDelivery=original.events.find(e=>e.id==="delivery")?.route;
  const photo = variant.events.find(e=>e.id==="photo");
  const setup = variant.events.find(e=>e.id==="setup");
  const bridgeEnd = world.connections.find(c=>c.id===world.visitorClosure.connectionId)?.windows[0].end ?? world.horizon;
  const location=(id:string,fallback:[number,number]):[number,number]=>world.entities.find(e=>e.id===id)?.visual.position??fallback;
  const plaza=location("plaza",[4.1,1]),pier=location("pier",[-2.7,2.5]);
  const related=new Set<string>();
  const trace=(id:string)=>{if(related.has(id))return;related.add(id);const result=variant.events.find(e=>e.id===id);for(const cause of result?.reasons.flatMap(r=>r.causes)??[])if(variant.events.some(e=>e.id===cause))trace(cause)};
  if(selected&&variant.events.some(e=>e.id===selected))trace(selected);
  return <><color attach="background" args={["#e8e4d9"]}/><ambientLight intensity={1.3}/><directionalLight position={[-4,10,6]} intensity={2.3} castShadow shadow-mapSize={[1024,1024]}/><group rotation={[0,-0.12,0]}>
    <Box position={[0,-0.22,0]} args={[16,0.35,10]} color="#d8d0b8"/><Box position={[0,-0.025,0]} args={[15.7,0.08,9.7]} color={ground}/>
    <Box position={[0,0.02,0.5]} args={[3,0.055,9.5]} color={water}/><Box position={[-3.65,0.045,-0.6]} args={[5.8,0.05,7.4]} color="#e9ddc2"/><Box position={[4.2,0.045,-0.6]} args={[5.3,0.05,7.4]} color="#eaddc3"/>
    <Box position={[0,0.16,-1]} args={[3.2,0.24,0.95]} color={bridgeEnd<=time?"#b9aca0":"#b58969"} onClick={()=>onSelect("bridge")}/><Box position={[0,0.35,-1.55]} args={[3.2,0.08,0.08]} color="#7d705e"/><Box position={[0,0.35,-0.45]} args={[3.2,0.08,0.08]} color="#7d705e"/>
    {bridgeEnd<=time && <Box position={[-1.3,0.42,-1]} args={[0.1,0.45,0.85]} color="#bd654f" onClick={()=>onSelect("bridge")}/>}
    {world.entities.filter(e=>["depot","bakery","townhall","gazette-site"].includes(e.visual.kind)&&e.visual.position).map(e=><Building key={e.id} x={e.visual.position![0]} z={e.visual.position![1]} color={e.visual.color} roof={e.id==="bakery"?"#8d8172":e.id==="depot"?terracotta:"#b57b62"} label={e.name} onClick={()=>onSelect(e.id==="gazette-site"?"gazette":e.id)}/>)}
    <Box position={[plaza[0],0.09,plaza[1]]} args={[2.8,0.07,2.6]} color={world.entities.find(e=>e.id==="plaza")?.visual.color??cream} onClick={()=>onSelect("plaza")}/><mesh position={[plaza[0],0.18,plaza[1]]}><cylinderGeometry args={[0.3,0.32,0.18,16]}/><meshStandardMaterial color="#b5b2a2"/></mesh><mesh position={[plaza[0],0.42,plaza[1]]}><sphereGeometry args={[0.15,12,8]}/><meshStandardMaterial color="#aec7c2"/></mesh>
    <Box position={[pier[0],0.11,pier[1]]} args={[2.0,0.1,0.6]} color={world.entities.find(e=>e.id==="pier")?.visual.color??"#9a8770"} onClick={()=>onSelect("pier")}/><Box position={[2.5,0.11,2.5]} args={[1.7,0.1,0.6]} color="#9a8770"/>
    <Box position={[pier[0]+1.4,0.08,pier[1]+0.35]} args={[0.75,0.13,0.42]} color="#777b71" onClick={()=>onSelect("ferry")}/>
    {[-6.7,-3.7,3.0,6.8].map((x,i)=><Tree key={i} x={x} z={i%2?2.9:-3} s={i%2?0.82:1}/>)}
    {world.entities.filter(e=>e.kind==="person"&&e.id!=="courier"&&e.visual.position).map(e=><Person key={e.id} x={e.visual.position![0]} z={e.visual.position![1]} color={e.visual.color} selected={selected===e.id} onClick={()=>onSelect(e.id)}/>)}
    {setup?.status==="possible" && setup.time!==null && time>=setup.time && <group onClick={()=>onSelect("setup")}><mesh position={[plaza[0]+0.15,0.1,plaza[1]+0.75]}><sphereGeometry args={[0.19,10,8]}/><meshStandardMaterial color="#d9979e"/></mesh><mesh position={[plaza[0]+0.45,0.1,plaza[1]+0.75]}><sphereGeometry args={[0.19,10,8]}/><meshStandardMaterial color="#e7b9a9"/></mesh></group>}
    {compare && photo?.status!=="possible" && time>=50 && <group onClick={()=>onSelect("photo")}><mesh rotation={[-Math.PI/2,0,0]} position={[plaza[0]+0.25,0.12,plaza[1]+0.75]}><ringGeometry args={[0.28,0.36,32]}/><meshBasicMaterial color="#2c6c77" transparent opacity={0.45} side={THREE.DoubleSide}/></mesh><mesh position={[plaza[0]+0.25,0.18,plaza[1]+0.75]}><sphereGeometry args={[0.14,10,8]}/><meshStandardMaterial color="#2c6c77" transparent opacity={0.35}/></mesh></group>}
    {delivery && <Van route={delivery} time={time} boat={delivery.connectionIds.includes("ferry")} onClick={()=>onSelect("delivery")}/>} {compare && originalDelivery && <><Line points={originalDelivery.path} color="#2c6c77" opacity={0.6} dashed/><Van route={originalDelivery} time={time} ghost/></>}
    {delivery && related.has("delivery") && <Line points={delivery.path} color={preview?"#d2a037":"#bb654a"} opacity={0.85} dashed={preview}/>}
  </group></>;
}
export default function Diorama(props: { world:World; variant:Simulation; original:Simulation; time:number; compare:boolean; preview:boolean; selected:string|null; onSelect:(id:string)=>void }) { return <Canvas shadows orthographic camera={{position:[13,15,18],zoom:53,near:0.1,far:100}} dpr={[1,1.7]} gl={{antialias:true,powerPreference:"low-power"}}><CameraRig/><WorldScene {...props}/></Canvas>; }
