import { createClient } from "@sanity/client";
import { loadEnvConfig } from "@next/env";
import { randomUUID } from "node:crypto";
import { fromDraftDocument } from "../src/sanity/adapter";
import { simulate } from "../src/engine/simulate";
import { pointerId, WORLD_ID } from "../src/sanity/read";
loadEnvConfig(process.cwd());
const projectId=process.env.NEXT_PUBLIC_SANITY_PROJECT_ID,dataset=process.env.NEXT_PUBLIC_SANITY_DATASET,token=process.env.SANITY_API_TOKEN;
if(!projectId||dataset!=="butterfly"||!token)throw new Error("Set a dedicated project ID, butterfly dataset and server-side SANITY_API_TOKEN");
const expected=process.argv.find(x=>x.startsWith("--expected-rev="))?.slice("--expected-rev=".length);
if(!expected)throw new Error("Pass --expected-rev=<pointer _rev> after reviewing the current pointer");
const client=createClient({projectId,dataset,token,useCdn:false,apiVersion:"2025-02-19"});
const [editing,published,pointer]=await Promise.all([client.getDocument(`drafts.butterfly.world.${WORLD_ID}`),client.getDocument(`butterfly.world.${WORLD_ID}`),client.getDocument<{worldId:string;_rev:string}>(pointerId)]);
const draft=editing??published;
if(!draft||!pointer||pointer.worldId!==WORLD_ID)throw new Error("Butterfly draft or pointer missing or world mismatch");
if(pointer._rev!==expected)throw new Error("Active pointer changed; review and evaluate again");
const world=fromDraftDocument(draft);if(world.id!==WORLD_ID)throw new Error("Draft world mismatch");
simulate(world);
const revisionId=`butterfly.revision.${randomUUID()}`;
const snapshot={...world,baseRevision:revisionId};simulate(snapshot);
await client.transaction().create({_id:revisionId,_type:"butterflyWorldRevision",worldId:WORLD_ID,revisionId,snapshotJson:JSON.stringify(snapshot),createdAt:new Date().toISOString()}).patch(pointerId,p=>p.ifRevisionId(expected).set({activeRevisionId:revisionId})).commit();
console.log(`Published frozen Butterfly revision ${revisionId}`);
